language: cpp
sudo: required
compiler:
  - gcc
  - clang

services:
  - docker

install:
  # Pull Docker image
  - docker pull tatsy/ubuntu-cxx

  # Dynamically generate Dockerfile
  - sed -e "s/@TRAVIS_C_COMPILER@/$CC/;s/@TRAVIS_CXX_COMPILER@/$CXX/" Dockerfile.in > Dockerfile

  # Build Dockerfile
  - docker build --tag=spica-env .

script:
  # Run test on Docker container
  - docker run -e CI=true -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -it spica-env /bin/bash -c "coveralls-lcov --repo-token RiYcPJSCbPZoogMd1PE10696EAqG8sl5q coverage.info"

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
