language: cpp
sudo: required
compiler:
  - gcc

before_install:
  # Install required packages
  - sudo apt -qq update
  # - sudo apt -qq upgrade
  - sudo apt -qq install build-essential software-properties-common cmake lcov
  - sudo apt -qq install byobu curl wget git htop man unzip vim wget subversion
  - if [ $TRAVIS_BRANCH = "master" ]; then sudo apt-get -qq install doxygen; fi

  # Install gcc/g++ v7
  - sudo add-apt-repository -yy ppa:ubuntu-toolchain-r/test
  - sudo apt -qq update
  - sudo apt install -qq gcc-7 g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - gcc --version
  - g++ --version
  - export CC=gcc
  - export CXX=g++

  # Install GoogleTest
  - git clone --depth=1 -b release-1.8.0 https://github.com/google/googletest.git
  - mkdir googletest/build && cd googletest/build
  - cmake -D CMAKE_BUILD_TYPE=Release .. && make -j4
  - sudo make install
  - cd ../../

  # Install Gcovr
  - sudo apt-get -qq install python-pip ruby
  - sudo pip install gcovr
  - sudo gem install coveralls-lcov

install:
  # Build
  - mkdir build && cd build
  - cmake -D CMAKE_BUILD_TYPE=Release -D SPICA_BUILD_MAIN=ON -D SPICA_BUILD_TESTS=ON -D WITH_SSE=ON ..
  - cmake --build .

before_script:
  - lcov --directory . --zerocounters

script:
  # Testing
  - make check

after_success:
  ## Collect coverage data
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' 'CMakeFiles/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token RiYcPJSCbPZoogMd1PE10696EAqG8sl5q coverage.info

before_deploy:
  - sudo pip install sphinx breathe sphinx_rtd_theme
  - "cd docs; /bin/bash deploy.sh; cd -"
  - mkdir packages
  - tar czvf packages/releases-$TRAVIS_TAG.tar.gz $(ls -I packages)
  - zip -q packages/releases-$TRAVIS_TAG.zip -r $(ls -I packages)

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WR9ks1pmxzB6QBS+8lJNxGpZIhaBzgK4luAQm4zeTGOFCZp12GoLZ9lTo1OOb+omwrjFx43/n/NqwFPNVR6ugWdo9Iu3U+kqsl2Ygk+97dJNg1gYDmvKr7UkTHU/O+1f6QP6aQkJT/HWaD7m4bKeNVc+WWy8B2e2FPpMfhsH+GA=
  file:
    - packages/releases-$TRAVIS_TAG.tar.gz
    - packages/releases-$TRAVIS_TAG.zip
  on:
    tags: true
    condition: $CXX=g++

branches:
  only:
    - master
    - development
    - "/v?[0-9\\.]+/"

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
