language: cpp
sudo: required
compiler:
  - gcc
  - clang

services:
  - docker

install:
  # Pull Docker image
  - docker pull tatsy/ubuntu-cxx

  # Dynamically generate Dockerfile
  - sed -e "s/@TRAVIS_C_COMPILER@/$CC/;s/@TRAVIS_CXX_COMPILER@/$CXX/" Dockerfile.in > Dockerfile

  # Build Dockerfile
  - docker build --tag=spica-env .

script:
  # Run test on Docker container
  - docker cp spica-env:/root/spica/coverage.info .

after_success:
  # Send coverage report to Coveralls
  - lcov --remove coverage.info '3rdparty/*' 'src/renderer/*' 'src/viewer/*' 'test/*' 'example/*' '/usr/*' 'CMakeFiles/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token RiYcPJSCbPZoogMd1PE10696EAqG8sl5q coverage.info

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
