language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
install:
  # install freeglut and glew
  - sudo apt-get -qq install freeglut3 freeglut3-dev libglew-dev libglew1.8 

  # install GTest
  - sudo apt-get install libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib; cd -"
  - export GTEST_LIBRARY=/usr/local/lib/libgtest.a
  - export GTEST_MAIN_LIBRARY=/usr/local/lib/libgtest_main.a
  - export GTEST_INCLUDE_DIRS=/usr/include

  # install lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - lcov --version
  - g++ --version

  # build spica
  - cmake .
  - cmake --build .
before_script:
  - lcov --directory . --zerocounters
script:
  - CTEST_OUTPUT_ON_FAILURE=TRUE make check
after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'test/*' 'example/*' '/usr/*' 'CMakeFiles/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token RiYcPJSCbPZoogMd1PE10696EAqG8sl5q coverage.info
  # - ./build/bin/simplept
  # - sh ./update-gh-pages.sh
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    secure: FvLmuzyUsyy8PN3u/RjsZUt4mUsuuAdG4O4FdSogAPFVeu1oathhntC8q4x1Qw7aQ+5Tper0yX7oJxKHjyuh3oCU+eNHMHGcpj1L21QzzEglUtzS/NW2/QhINt1WXB3onCxhcL9lq+NzWMOdCqPAfe/egbNX/ERCTrGZMtoFNgo=
