language: cpp
sudo: required
compiler:
  - gcc
  - clang

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - if [ $TRAVIS_BRANCH = "master" ]; then sudo apt-get -qq install doxygen; fi

install:
  # Pull Docker image
  - docker pull tatsy/ubuntu-cxx:default

  # Dynamically generate Dockerfile
  - sed -i -e "s/@C_COMPILER@/$CC/;s/@CXX_COMPILER@/$CXX/;s/@BRANCH_NAME@/$TRAVIS_BRANCH/;s/@PULL_REQUEST@/$TRAVIS_PULL_REQUEST/" Dockerfile

  # Build Dockerfile
  - docker build --tag=spica-env .

  # Run container
  - docker run --name spica-env --env="CI=true" --env="TRAVIS_JOB_ID=$TRAVIS_JOB_ID" --env="CTEST_OUTPUT_ON_FAILURE=TRUE" -c 2048 -m 8192m -itd spica-env

script:
  # Run test on Docker container
  - docker exec spica-env make check

after_success:
  ## Collect coverage data
  - if [ $CXX = "g++"     ]; then docker exec spica-env lcov --directory . --capture --output-file coverage.info; fi
  - if [ $CXX = "clang++" ]; then docker exec spica-env lcov --directory . --capture --output-file coverage.info --gcov-tool llvm-cov-3.5; fi
  - docker exec spica-env lcov --remove coverage.info '3rdparty/*' 'sources/renderer/*' 'sources/viewer/*' 'sources/bsdf/*' 'test/*' 'example/*' '/usr/*' 'CMakeFiles/*' --output-file coverage.info
  - docker exec spica-env lcov --list coverage.info
  - docker exec spica-env coveralls-lcov --repo-token RiYcPJSCbPZoogMd1PE10696EAqG8sl5q coverage.info

before_deploy:
  - "cd docs; /bin/bash deploy.sh; cd -"
  - mkdir packages
  - tar czvf packages/releases-$TRAVIS_TAG.tar.gz $(ls)
  - zip -q packages/releases-$TRAVIS_TAG.zip -r $(ls)

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FvLmuzyUsyy8PN3u/RjsZUt4mUsuuAdG4O4FdSogAPFVeu1oathhntC8q4x1Qw7aQ+5Tper0yX7oJxKHjyuh3oCU+eNHMHGcpj1L21QzzEglUtzS/NW2/QhINt1WXB3onCxhcL9lq+NzWMOdCqPAfe/egbNX/ERCTrGZMtoFNgo=
  file:
    - packages/releases-$TRAVIS_TAG.tar.gz
    - packages/releases-$TRAVIS_TAG.zip
  on:
    tags: true
    condition: $CXX=clang++

branches:
  only:
    - master
    - development

env:
  global:
    secure: FvLmuzyUsyy8PN3u/RjsZUt4mUsuuAdG4O4FdSogAPFVeu1oathhntC8q4x1Qw7aQ+5Tper0yX7oJxKHjyuh3oCU+eNHMHGcpj1L21QzzEglUtzS/NW2/QhINt1WXB3onCxhcL9lq+NzWMOdCqPAfe/egbNX/ERCTrGZMtoFNgo=

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
