language: cpp

compiler:
  - gcc

before_install:
  # update g++
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90

  # install Qt5
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install -qq qt5-default qttools5-dev-tools

  # update cmake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
  - tar xf cmake-3.2.2.tar.gz
  - cd cmake-3.2.2
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j4
  - sudo make install
  - sudo ldconfig
  - cd ../..

install:
  # install freeglut and glew
  - sudo apt-get -qq install freeglut3 freeglut3-dev libglew-dev libglew1.5
  - sudo apt-get -qq install libxmu-dev libxi-dev

  # install GTest
  - sudo apt-get install libgtest-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib; cd -"
  - export GTEST_LIBRARY=/usr/local/lib/libgtest.a
  - export GTEST_MAIN_LIBRARY=/usr/local/lib/libgtest_main.a
  - export GTEST_INCLUDE_DIRS=/usr/include

  # install lcov
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  - lcov --version
  - g++ --version
  - cmake --version

  # build spica
  - cmake .
  - cmake --build .

before_script:
  - lcov --directory . --zerocounters

script:
  - CTEST_OUTPUT_ON_FAILURE=TRUE make check

after_success:
  - lcov --no-checksum --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'test/*' 'example/*' '/usr/*' 'CMakeFiles/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token RiYcPJSCbPZoogMd1PE10696EAqG8sl5q coverage.info

branches:
  only:
    - master
    - develop

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always

env:
  global:
    secure: FvLmuzyUsyy8PN3u/RjsZUt4mUsuuAdG4O4FdSogAPFVeu1oathhntC8q4x1Qw7aQ+5Tper0yX7oJxKHjyuh3oCU+eNHMHGcpj1L21QzzEglUtzS/NW2/QhINt1WXB3onCxhcL9lq+NzWMOdCqPAfe/egbNX/ERCTrGZMtoFNgo=
